version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:YourSecurePassword@db:5432/fastapi_db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: YourSecurePassword
      POSTGRES_DB: fastapi_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
